### ISSUE TITLE
Add command to create a RHOSAK cluster from VS Code

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-rhoas#1]
@wtrocki any pointers on the API to call to do that?

**Comment by wtrocki** [comment]
@fbricon please check openapi docs. Btw. We going to work on typescript SDK that could be used after that.

**Comment by fbricon** [comment]
@wtrocki what's the ETA on the sdk?

**Comment by wtrocki** [comment]
@fbricon that is actually good question. If you look to get something fast we can publish already existing package in kas-ui and later incrementally build on top of it. 

https://github.com/bf2fc6cc711aee1a0c2a/kas-ui/tree/main/src/openapi 

That will be plain API calls without authentication shenanigans. For the documented and officially supported SDK we talk about couple weeks time.

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by fbricon** [comment]
@wtrocki there's no rush, I can try to hack something quick  on my side without the sdk. 
Will tI be able to use the SDK with the access tokens managed by VS Code?

**Comment by wtrocki** [comment]
> I can try to hack something quick on my side without the sdk.

I would not recommend it. It is so easy to generate client from typescript and I would strongly advice to do so or we can pulblish some package for it so your repo will not have any source code that is generated

**Comment by fbricon** [comment]
I'm just doing some quick experimentation to see what would the workflow be on the vscode side. Not anything that I'd publicly release given the SDK is on its way.

**Comment by wtrocki** [comment]
Just to be clear. Sdk will be contacting 99% of the code generated from openapi as in kas-ui. So using this code will be like using sdk without having it

**Comment by fbricon** [comment]
depends on https://github.com/redhat-developer/app-services-sdk-js/issues/1
